### ISSUE TITLE
Embed links are all unavailable

### ISSUE THREAD

**Issue by ntsanq** [aalaap/faker-youtube#13]
Every link that being generated is not available.
Do you have any way to update or solve this?

**Comment by aalaap** [comment]
Every link is fake! This is only dummy data for testing.

**Comment by ntsanq** [comment]
Do we have way to have a real youtube video?

**Comment by aalaap** [comment]
That's not what this library is designed for.

You may consider using the official YouTube Data API methods such as [search](https://developers.google.com/youtube/v3/docs/search/list) or [list](https://developers.google.com/youtube/v3/docs/videos/list). You will need to register for an API key.
