### ISSUE TITLE
[Feature Request] Random real video URL?

### ISSUE THREAD

**Issue by LetsDoGood** [aalaap/faker-youtube#5]
Sometimes one would want to generate a random but real & existing youtube video url, so various aspects of dealing with real youtube videos can be automated/tested.

Useful:
[How do I get a random YouTube video with the YouTube API?
](https://stackoverflow.com/questions/11315416/how-do-i-get-a-random-youtube-video-with-the-youtube-api)I like the [2nd answer](https://stackoverflow.com/a/13373945) there

**Comment by aalaap** [comment]
Then it wouldn't exactly live up to the `faker` part of the name, would it? :smile: 

The answer you've linked to (which also explains how the random YouTube URL website works) suggests a plain brute-force method, which should be easy to implement on it's own as a separate package. I don't think that is within the scope of this Faker generator.

Faker generated data is only intended for local testing, for eg. validations of a model that contains video URLs. If you're checking the actual validity of the fake data, then there is something wrong with your tests and/or you shouldn't be using Faker in the first place.

**Comment by LetsDoGood** [comment]
Fair enough 😁

**Comment by LetsDoGood** [comment]
In truth though one could argue that since Faker seed data is usually used for purposes of filling content into an application to be able to test all of its functionality, so let's say if the application processes Addresses into geo coordinates, or fetches Tweets from a given twitter account, or reads some properties of a youtube Video via API etc. then developers would desire a data seeding/generator that can also produce "real" such data to work with; real addresses, real twitter accounts, real youtube videos etc.

On the other hand perhaps that doesn't belong in a "Faker" kind of library, but rather in a similar-but-kinda-different "Test Data Generator" library. For me this Faker library always seemed to be that; it seems to be more/all about generating test data rather than specifically being "fake" data. It's only "Fake" in the sense that it isn't a live production application used by end-users. More like "Placeholder" seeding rather than specifically being invalid/non-existent/wrong data.

Perhaps ideally there would be a Test Data Generator library which can generate fake and/or real data as desired.
