### ISSUE TITLE
Faker Support for future versions

### ISSUE THREAD

**Issue by garbinmarcelo** [aalaap/faker-youtube#9]
Hi, has this package been abandoned? 

I was trying to use it with the new Faker repository ([https://github.com/FakerPHP/Faker](https://github.com/FakerPHP/Faker)), but without success.

Thank's

**Comment by aalaap** [comment]
What's wrong? I'll see if I can fix it. Or you can send a PR if you know what the problem is.

**Comment by garbinmarcelo** [comment]
![image](https://user-images.githubusercontent.com/9335588/98297509-47315100-1f93-11eb-99c1-8e168f74b13a.png)

**Comment by aalaap** [comment]
Wow, I'm only now reading about the new Faker and why.

Thanks for bringing this to my attention! I'll see what I can do.

**Comment by garbinmarcelo** [comment]
I thank you for your attention. I was also surprised by the changes to the repository that was "official".

**Comment by aalaap** [comment]
Yeah. I'll have to set this thing up over the weekend and figure it out.

Just like the author of the original Faker, I have moved on from PHP over to Node and React, but I see no reason for this add-on to die.

**Comment by aalaap** [comment]
This should work now.

Enjoy your weekend!
